services:
  frontend:
    build: ./frontend/.
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build: ./backend/.
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      timeout: 10s
      interval: 10s
      retries: 10