services:
  frontend:
    build: ./frontend/.
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
     - ./frontend/src/:/app/src
  backend:
    build: ./backend/.
    ports:
      - 4000:4000
    volumes:
      - ./backend/src/:/app/src